# epel, RPMForge, remi リポジトリを追加する
- yum:
    name:
      - http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel//epel-release-latest-7.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  tags: yum_repos

# 明示的に指定したいのでenabledは全て0にする
- replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo
    - remi.repo
  tags: yum_repos
