# epel, RPMForge, remi リポジトリを追加する
- yum: name={{item}}
  with_items:
    - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
    - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  tags: yum_repos

# 明示的に指定したいのでenabledは全て0にする
- replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo
    - rpmforge.repo
    - remi.repo
  tags: yum_repos
