# Apacheのインストール
- name: install packages httpd
  yum: name=httpd state=latest
  tags: httpd

# Userをvagrantにする
- name: replace User name
  replace: dest=/etc/httpd/conf/httpd.conf regexp="User apache" replace="User vagrant"
  tags: httpd

# Groupをvagrantにする
- name: replace Group name
  replace: dest=/etc/httpd/conf/httpd.conf regexp="Group apache" replace="Group vagrant"
  tags: httpd

# Vagrantで共有データの更新が行われないことがあるので
# Sendfileをoffにしておく
- name: replace Sendfile
  replace: dest=/etc/httpd/conf/httpd.conf regexp="EnableSendfile on" replace="EnableSendfile off"
  tags: httpd

# ScriptAliasをコメントアウトする
- name: commentout ScriptAlias
  replace: dest=/etc/httpd/conf/httpd.conf regexp="ScriptAlias \/cgi-bin\/" replace="# ScriptAlias off \/cgi-bin\/"
  tags: httpd

# VirtualDocumentRootを追加する
- name: append virtual conf
  copy: src=virtual.conf dest=/etc/httpd/conf.d/virtual.conf owner=root group=root mode=0644
  tags: httpd

# httpdを起動する
- name: httpd is runnning and enabled
  service: name=httpd state=running enabled=yes
  tags: httpd
