- name: Install libtidy
  yum: name=libtidy state=latest enablerepo=epel

- name: Install php-tidy
  yum: name=php-tidy state=latest enablerepo=remi,remi-php56

- name: Install phpMyAdmin
  yum: name=phpMyAdmin state=latest enablerepo=remi,remi-php56

- name: Change phpMyAdmin Access Privileges for Apache 2.2
  replace: >
    dest=/etc/httpd/conf.d/phpMyAdmin.conf
    regexp=" Deny from All"
    replace=" #Deny from All"

- name: Change phpMyAdmin Access Privileges for Apache 2.4
  replace: >
    dest=/etc/httpd/conf.d/phpMyAdmin.conf
    regexp=" Require local"
    replace=" Require all granted"
